In [0]:
import tensorflow as tf 
tf.test.gpu_device_name()

''

# New Section

RUL


In [0]:
! pip install pandas

In [0]:
import io

In [0]:
import pandas as pd

In [0]:

!pwd

/content


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import preprocessing

In [0]:
train_df = pd.read_csv('/content/drive/My Drive/sensor.csv',header=0)
train_df.drop(train_df.columns[[17]], axis=1, inplace=True)

In [0]:
'''
for i in range(2,54):
  #target = train_df[i]
  target = train_df.iloc[:, i]
  print(target)
  train_df = train_df.assign(InterpolateSLinear=train_df.target.interpolate(method='slinear'))
'''
#train_df = train_df.interpolate(method ='slinear', limit_direction ='forward') 
train_df = train_df.interpolate(method = 'linear' , order = 2 , limit_direction ='forward') 
#train_df.interpolate()
#train_df[1]

In [0]:
train_df.insert(54, "RUL", 0)  


In [0]:
train_df

Unnamed: 0            timestamp  ...  machine_status  RUL
0                0  2018-04-01 00:00:00  ...          NORMAL    0
1                1  2018-04-01 00:01:00  ...          NORMAL    0
2                2  2018-04-01 00:02:00  ...          NORMAL    0
3                3  2018-04-01 00:03:00  ...          NORMAL    0
4                4  2018-04-01 00:04:00  ...          NORMAL    0
...            ...                  ...  ...             ...  ...
220315      220315  2018-08-31 23:55:00  ...          NORMAL    0
220316      220316  2018-08-31 23:56:00  ...          NORMAL    0
220317      220317  2018-08-31 23:57:00  ...          NORMAL    0
220318      220318  2018-08-31 23:58:00  ...          NORMAL    0
220319      220319  2018-08-31 23:59:00  ...          NORMAL    0

[220320 rows x 55 columns]

In [0]:
k = 0
for i in range(len(train_df)):
    if(train_df["machine_status"][i] == "BROKEN" ):
        count = 0
        for j in range(i,k-1,-1):
            train_df.at[j,'RUL']= count
            count = count + 1
        k = i

In [0]:
n = len(train_df)-1
while(train_df["machine_status"][n] != "BROKEN"):
    n -= 1   
train_df = train_df[:n+1]        
train_df["machine_status"][n+1] = 0    

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:205: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_n

In [0]:
from pandas import read_csv, DataFrame
from numpy.random import seed
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from keras.layers import Input, Dense
from keras.models import Model

Using TensorFlow backend.


In [0]:
train_df.drop(['machine_status'], axis=1, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
train_df.drop(['Unnamed: 0'], axis=1, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
train_df

timestamp  sensor_00  sensor_01  ...  sensor_50  sensor_51    RUL
0       2018-04-01 00:00:00   2.465394  47.092010  ...   243.0556   201.3889  17155
1       2018-04-01 00:01:00   2.465394  47.092010  ...   243.0556   201.3889  17154
2       2018-04-01 00:02:00   2.444734  47.352430  ...   241.3194   203.7037  17153
3       2018-04-01 00:03:00   2.460474  47.092010  ...   240.4514   203.1250  17152
4       2018-04-01 00:04:00   2.445718  47.135410  ...   242.1875   201.3889  17151
...                     ...        ...        ...  ...        ...        ...    ...
166436  2018-07-25 13:56:00   2.313889  45.833330  ...  1000.0000   198.2060      4
166437  2018-07-25 13:57:00   2.315856  45.833332  ...  1000.0000   202.8356      3
166438  2018-07-25 13:58:00   2.322743  45.833330  ...  1000.0000   206.8866      2
166439  2018-07-25 13:59:00   2.315856  45.789930  ...  1000.0000   209.7801      1
166440  2018-07-25 14:00:00   2.318808  45.833332  ...  1000.0000   205.7292      0

[166441 rows x 53 columns]

Multi class Classification using LSTM


In [0]:
period1 = 50
period2 = 300

In [0]:
train_df.insert(53, "lab_bin", 0)

In [0]:
for i in range(len(train_df)):
    if(train_df["RUL"][i] < period1):
        train_df.at[i,'lab_bin'] = 1    
    elif(train_df["RUL"][i] < period2):
        train_df.at[i,'lab_bin'] = 2


In [0]:
train_df    

timestamp  sensor_00  sensor_01  ...  sensor_51    RUL  lab_bin
0       2018-04-01 00:00:00   2.465394  47.092010  ...   201.3889  17155        0
1       2018-04-01 00:01:00   2.465394  47.092010  ...   201.3889  17154        0
2       2018-04-01 00:02:00   2.444734  47.352430  ...   203.7037  17153        0
3       2018-04-01 00:03:00   2.460474  47.092010  ...   203.1250  17152        0
4       2018-04-01 00:04:00   2.445718  47.135410  ...   201.3889  17151        0
...                     ...        ...        ...  ...        ...    ...      ...
166436  2018-07-25 13:56:00   2.313889  45.833330  ...   198.2060      4        1
166437  2018-07-25 13:57:00   2.315856  45.833332  ...   202.8356      3        1
166438  2018-07-25 13:58:00   2.322743  45.833330  ...   206.8866      2        1
166439  2018-07-25 13:59:00   2.315856  45.789930  ...   209.7801      1        1
166440  2018-07-25 14:00:00   2.318808  45.833332  ...   205.7292      0        1

[166441 rows x 54 columns]

In [0]:
import numpy as np

import matplotlib.pyplot as plt

from sklearn import metrics

from sklearn import model_selection

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC, LinearSVC

from sklearn.metrics import roc_auc_score,roc_curve
from sklearn.model_selection import KFold

In [0]:
y = pd.get_dummies(train_df['lab_bin']).values
X = train_df.iloc[:, 1:52]

In [0]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [0]:
def calcp(a):
  l=[]
  for j in range(3): 
    summ = 0
    for i in range(3):
      summ = summ + a[i][j]
    l.append(a[j][j]/summ)
  return l

def calcr(a):
  l=[]
  for i in range(3):
    summ = 0
    for j in range(3):
      summ = summ + a[i][j]
    l.append(a[i][i]/summ)
  return l

In [0]:
# kf = KFold(n_splits=2)
# kf.get_n_splits(X)

# for train_index, test_index in kf.split(X):
#     print("TRAIN:", train_index, "TEST:", test_index)
#     X_train, X_test = X.iloc[train_index], X.iloc[test_index]
#     Y_train, Y_test = y[train_index], y[test_index]

#     sc_X = StandardScaler()
#     X_train =sc_X.fit_transform(X_train)
#     X_test = sc_X.transform(X_test)

    
#     classifier = MLPClassifier()
#     classifier.fit(X_train, Y_train)

#     y_pred = classifier.predict(X_test)

#     cm = confusion_matrix(Y_test, y_pred)
#     print(cm)
#     print(metrics.accuracy_score(Y_test, y_pred, normalize=True))
#     print(calcp(cm))
#     print(calcr(cm))

# # X.head()
# # X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.6, random_state = seed(20))


In [0]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [0]:

X.head()
X_train, X_test, Y_train, Y_test = train_test_split(X, y, train_size = 0.6, random_state = seed(20))

sc_X = StandardScaler()
X_train =sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)



In [0]:
n_features = len(X_train[0])
n_steps = 1

In [0]:
X_train= X_train.reshape((len(X_train), n_steps, n_features))
X_test=X_test.reshape((len(X_test), n_steps, n_features))

In [0]:
X_train.shape

(99864, 1, 51)

In [0]:

model = Sequential()
# model.add(LSTM(50, activation='relu', input_shape=(1, n_features)))
# model.add(Dense(1))
# model.compile(optimizer='adam', loss='mse')
model.add(LSTM(10, dropout=0.2, recurrent_dropout=0.2,input_shape=(1, n_features)))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=10, verbose=1)
ypred = model.predict(X_test, verbose=1)






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





99864/99864 [==============================] - 9s 94us/step - loss: 0.0937 - acc: 0.9806
Epoch 2/10
99864/99864 [==============================] - 9s 89us/step - loss: 0.0373 - acc: 0.9905
Epoch 3/10
99864/99864 [==============================] - 9s 88us/step - loss: 0.0320 - acc: 0.9911
Epoch 4/10
99864/99864 [==============================] - 8s 84us/step - loss: 0.0290 - acc: 0.9918
Epoch 5/10
99864/99864 [==============================] - 9s 87us/step - loss: 0.0270 - acc: 0.9920
Epoch 6/10
99864/99864 [==============================] - 8s 84us/step - loss: 0.0251 - acc: 0.9925
Epoch 7/10
99864/99864 [==============================] - 9s 85us/step - loss: 0.0238 - acc: 0.9928
Epoch 8/10
99864/99864 [==============================] - 9s 88us/step - loss

In [0]:
y_pred= []
for i in ypred:
  y_pred.append(np.argmax(i))
print(y_pred)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [0]:
y_test= []
for i in Y_test:
  y_test.append(np.argmax(i))
print(y_test)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [0]:
# y_test= np.array(y_test)
# y_test.reshape(len(y_test),1)
# print(y_test)

In [0]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(metrics.accuracy_score(y_test, y_pred, normalize=True))
print(calcp(cm))
print(calcr(cm))

[[65725     2    34]
 [   43    10    80]
 [  137     0   546]]
0.9955540201571114
[0.9972687959942341, 0.8333333333333334, 0.8272727272727273]
[0.9994525630692964, 0.07518796992481203, 0.7994143484626647]


LSTM with multiple time steps as input for multiclass





In [0]:
train_df

timestamp  sensor_00  sensor_01  ...  sensor_51    RUL  lab_bin
0       2018-04-01 00:00:00   2.465394  47.092010  ...   201.3889  17155        0
1       2018-04-01 00:01:00   2.465394  47.092010  ...   201.3889  17154        0
2       2018-04-01 00:02:00   2.444734  47.352430  ...   203.7037  17153        0
3       2018-04-01 00:03:00   2.460474  47.092010  ...   203.1250  17152        0
4       2018-04-01 00:04:00   2.445718  47.135410  ...   201.3889  17151        0
...                     ...        ...        ...  ...        ...    ...      ...
166436  2018-07-25 13:56:00   2.313889  45.833330  ...   198.2060      4        1
166437  2018-07-25 13:57:00   2.315856  45.833332  ...   202.8356      3        1
166438  2018-07-25 13:58:00   2.322743  45.833330  ...   206.8866      2        1
166439  2018-07-25 13:59:00   2.315856  45.789930  ...   209.7801      1        1
166440  2018-07-25 14:00:00   2.318808  45.833332  ...   205.7292      0        1

[166441 rows x 54 columns]

In [0]:
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)


In [0]:
from numpy import array
from numpy import hstack

dataset = pd.concat([train_df.iloc[:, 1:52], train_df['lab_bin']], axis=1)
# define input sequence
dataset = dataset.to_numpy()
print(dataset)
# choose a number of time steps
n_steps = 100
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(y)
y = pd.get_dummies(y).values
print(X.shape, y.shape)

n_features = X.shape[2]
# define model


[[   2.465394     47.09201      53.2118     ...  243.0556
   201.3889        0.        ]
 [   2.465394     47.09201      53.2118     ...  243.0556
   201.3889        0.        ]
 [   2.444734     47.35243      53.2118     ...  241.3194
   203.7037        0.        ]
 ...
 [   2.322743     45.83333      52.99479    ... 1000.
   206.8866        1.        ]
 [   2.315856     45.78993      53.03819    ... 1000.
   209.7801        1.        ]
 [   2.318808     45.83333206   52.99479    ... 1000.
   205.7292        1.        ]]
[0. 0. 0. ... 1. 1. 1.]
(166342, 100, 51) (166342, 3)


In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, train_size = 0.6, random_state = seed(20))

In [0]:
from pandas import read_csv, DataFrame
from numpy.random import seed
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras import metrics

In [0]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=[metrics.mae,metrics.categorical_accuracy])
# fit model


In [0]:
model.fit(X_train, Y_train, epochs=1, verbose=1)


Epoch 1/1
99805/99805 [==============================] - 204s 2ms/step - loss: 2.2901 - mean_absolute_error: 0.0950 - categorical_accuracy: 0.8575


In [0]:
yhat = model.predict(X_test, verbose=0)
print(yhat)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [0]:
y_pred = []
for i in yhat:
  if i[0]:
    y_pred.append(0)
  elif i[1]:
    y_pred.append(1)
  else:
    y_pred.append(2)
y_test = []
for i in Y_test:
  if i[0]:
    y_test.append(0)
  elif i[1]:
    y_test.append(1)
  else:
    y_test.append(2)

In [0]:
from sklearn import metrics
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(metrics.accuracy_score(y_test, y_pred, normalize=True))
print(calcp(cm))
print(calcr(cm))

[[64263  1266   174]
 [  129     3     1]
 [  679    19     3]]
0.9659137021506831
[0.9875827941786663, 0.002329192546583851, 0.016853932584269662]
[0.9780831925482855, 0.022556390977443608, 0.0042796005706134095]
